name: GitHub Actions Build

on:
  push:
    branches:
      - master
    # 只在下列路径变更时触发
    paths:
      - 'packages/**'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Run Script
        run: pnpm install && pnpm build

      - name: Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          push-branch: master
          commit-message: 'Update libs by Github Actions'
          files: libs/
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
